### ISSUE TITLE
Getting weird syntax error when updating an existing comment

### ISSUE THREAD

**Issue by tchap** [MattyIce/steem-keychain#57] opened 2018-11-22 01:14 UTC
When trying to update a comment, Chrome is throwing

```
Uncaught SyntaxError: Invalid or unexpected token
```

The error takes me to the source I am attaching. What is marked as a syntax error is the `"body"` diff string on the first line.

[steem_keychain_syntax_error.txt](https://github.com/MattyIce/steem-keychain/files/2606259/steem_keychain_syntax_error.txt)

Not even sure where that error is coming from, but I am using the same diff when posting using SteemConnect and I've never had any issues with that.

The call actually succeeds and the comment is updated, but then it crashes on this error and the response is not returned to the application and the whole web app ends up in a weird state.

**Comment by stoodkev** [comment] 2019-02-21 06:36
Yes,dupe of #37 , I ll investigate the issue.

**Closed by stoodkev** 2019-02-21 06:36 UTC
